# Generated by Django 4.2.2 on 2023-08-05 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('updated_by', models.CharField(auto_created=True, default='admin', max_length=250)),
                ('created_by', models.CharField(auto_created=True, default='admin', max_length=250)),
                ('status', models.CharField(auto_created=True, choices=[('En proceso', 'En proceso'), ('Descartada', 'Descartada'), ('Verificado', 'Verificado')], default='En proceso', max_length=500)),
                ('id', models.AutoField(default=uuid.UUID('2685f5d7-bd36-4bc8-9ffa-1b1be5379e56'), max_length=250, primary_key=True, serialize=False)),
                ('incident', models.CharField(max_length=250)),
                ('incident_type', models.CharField(choices=[('Derrame', 'Derrame'), ('Incendio', 'Incendio'), ('Lesión', 'Lesión')], max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
