# Generated by Django 4.2.2 on 2023-08-05 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.AutoField(default=uuid.UUID('1afa2016-212c-46c3-b270-4b7f51bd583b'), primary_key=True, serialize=False),
        ),
    ]
