# Generated by Django 4.2.2 on 2023-08-05 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapi', '0003_alter_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.CharField(default=uuid.UUID('d58e3aaf-6505-4cc1-babf-a1c504931243'), max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
