# Generated by Django 4.2.2 on 2023-08-28 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidentapi', '0004_alter_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.CharField(auto_created=True, default=uuid.UUID('bd7dd22c-3391-4138-9240-141732f95741'), max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Derrame', 'Derrame'), ('Incendio', 'Incendio'), ('Caida', 'Caida')], max_length=250),
        ),
    ]
